### ISSUE TITLE
Socket EOFError

### ISSUE THREAD

**Issue by dulacp** [InviteBox/django-live-profiler#10]
I'm running the command `$ aggregated --host 127.0.0.1 --port 5557`
And when I try to load the url http://127.0.0.1:8000/profiler/ it raises the **Socket EOFError**.

Here is the Traceback

``` sh
Traceback (most recent call last):
  File "/Users/peteralaoui/Sites/Powergun/rocky-mountain-6109/venv/bin/aggregated", line 9, in <module>
    load_entry_point('django-live-profiler==0.0.8', 'console_scripts', 'aggregated')()
  File "/Users/peteralaoui/Sites/Powergun/rocky-mountain-6109/venv/src/django-live-profiler/aggregate/server.py", line 80, in main
    q = socket.recv_pyobj()
  File "/Users/peteralaoui/Sites/Powergun/rocky-mountain-6109/venv/lib/python2.7/site-packages/zmq/core/pysocket.py", line 294, in recv_pyobj
    return pickle.loads(s)
EOFError
```

I will investigate on my side why is it crashing.
Do you think it's because I'm running inside a virtualenv ?

**Comment by dulacp** [comment]
I'm answering to my own issue ^^
I read the source code, and find that the default port is not `5557` but `5556`.
