### ISSUE TITLE
TypeError: setsockopt() argument 3 must be string or read-only buffer, not None

### ISSUE THREAD

**Issue by saboor97** [InviteBox/django-live-profiler#27]
saboor@ubuntu:~/staticdhcpd/staticDHCPd$ sudo python staticDHCPd
2019-03-29 12:23:40,990 : INFO : Console-based logging online
2019-03-29 12:23:40,991 : WARNING : ----------------------------------------
2019-03-29 12:23:40,991 : WARNING : ----------------------------------------
2019-03-29 12:23:40,991 : WARNING : ----------------------------------------
2019-03-29 12:23:40,991 : WARNING : System startup in progress; PID=29870
2019-03-29 12:23:40,991 : WARNING : staticDHCPd version 2.0.0-rc1 : http://uguu.ca/
2019-03-29 12:23:40,991 : WARNING : libpydhcpserver version 2.0.0-rc1 : http://uguu.ca/
2019-03-29 12:23:40,992 : WARNING : Continuing with subsystem initialisation
2019-03-29 12:23:40,992 : WARNING : ----------------------------------------
2019-03-29 12:23:40,992 : INFO : Webservice module enabled; configuring...
2019-03-29 12:23:41,049 : INFO : Prepared to bind to 0.0.0.0:30880
2019-03-29 12:23:41,051 : INFO : Configured Webservice engine
2019-03-29 12:23:41,053 : INFO : Webservice engine beginning normal operation
2019-03-29 12:23:41,058 : INFO : Webservice logging module enabled; configuring...
2019-03-29 12:23:41,059 : INFO : Configuring web-accessible logging...
2019-03-29 12:23:41,059 : INFO : Web-accessible logging online; buffer-size=200
2019-03-29 12:23:41,060 : INFO : Initialising custom code...
2019-03-29 12:23:41,109 : INFO : Prepared to bind to 192.168.1.1; ports: server: 67, client: 68, proxy: None; raw-response-interface: -
2019-03-29 12:23:41,159 : CRITICAL : System shutdown triggered by unhandled exception:
Traceback (most recent call last):
  File "staticDHCPd", line 294, in <module>
    _initialiseDHCP()
  File "staticDHCPd", line 224, in _initialiseDHCP
    dhcp = staticdhcpdlib.dhcp.DHCPService(database)
  File "/home/saboor/staticdhcpd/staticDHCPd/staticdhcpdlib/dhcp.py", line 865, in __init__
    database
  File "/home/saboor/staticdhcpd/staticDHCPd/staticdhcpdlib/dhcp.py", line 410, in __init__
    response_interface_qtags=response_interface_qtags,
  File "/home/saboor/staticdhcpd/staticDHCPd/libpydhcpserver/dhcp.py", line 115, in __init__
    self._network_link = _NetworkLink(str(server_address), server_port, client_port, proxy_port, response_interface, response_interface_qtags=response_interface_qtags)
  File "/home/saboor/staticdhcpd/staticDHCPd/libpydhcpserver/dhcp.py", line 285, in __init__
    (dhcp_socket, proxy_socket) = self._setupListeningSockets(server_port, proxy_port, server_address)
  File "/home/saboor/staticdhcpd/staticDHCPd/libpydhcpserver/dhcp.py", line 358, in _setupListeningSockets
    dhcp_socket.setsockopt(socket.SOL_SOCKET, _SO_BINDTODEVICE, listen_interface)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)

**Comment by pirate** [comment]
FYI I fixed this here: https://github.com/InviteBox/django-live-profiler/pull/28
